### ISSUE TITLE
Interlock -- Rename DeviceProfile Properties (C SDK) 

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/device-sdk-c#105]
See edgexfoundry/go-mod-core-contracts#59 for context.

References to the properties in the above issue need to be changed in device-sdk-c for integration.

**Comment by iain-anderson** [comment]
Already addressed in https://github.com/edgexfoundry/device-sdk-c/commit/67b49ac177871b243c237cd6fa6b082b73e197fa
