### ISSUE TITLE
Getting parsing error while running the sample device example 

### ISSUE THREAD

**Issue by debukhra** [edgexfoundry/device-sdk-c#158]
Hi,
I followed this link for device random using device-sdk-c.

https://docs.edgexfoundry.org/Ch-GettingStartedSDK-C.html

Device profile is : https://docs.edgexfoundry.org/_downloads/random-generator-device.yaml
Configuration profile is: https://docs.edgexfoundry.org/_downloads/configuration.toml

While running the ./device-example-c getting the following error 

**level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=Starting device-template device service, version 1.0
level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=EdgeX device SDK for C, version 1.0.1
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Service configuration follows:
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Writable/LogLevel=TRACE
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Logging/File=./device-simple.log
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Logging/EnableRemote=false
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/SendReadingsOnChanged=false
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/ProfilesDir=./res
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/MaxCmdResultLen=0
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/MaxCmdOps=128
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/Discovery=true
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Device/DataTransform=true
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Service/ConnectRetries=3
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Service/Timeout=5000
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Service/Port=49992
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Service/Host=172.17.0.1
level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=Found core-data service at 172.17.0.1:48080
level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=Found core-metadata service at 172.17.0.1:48081
level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=Processing Device Profiles from ./res
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=Checking existence of DeviceProfile RandNum-Device
level=ERROR ts=2019-07-19T09:59:45Z app=device-template msg=Unable to parse "1.0" as integer for transform "scale"
level=ERROR ts=2019-07-19T09:59:45Z app=device-template msg=Unable to parse "0.0" as integer for transform "offset"
level=ERROR ts=2019-07-19T09:59:45Z app=device-template msg=Error reading property for deviceResource randomnumber
level=ERROR ts=2019-07-19T09:59:45Z app=device-template msg=Parse error in device profile RandNum-Device
level=INFO ts=2019-07-19T09:59:45Z app=device-template msg=Uploading deviceprofile from ./res/random-generator-device.yaml
level=DEBUG ts=2019-07-19T09:59:45Z app=device-template msg=HTTP response 409 - Conflict
level=ERROR ts=2019-07-19T09:59:45Z app=device-template msg=Error uploading device profile**

How can I resolve this issue?

**Comment by iain-anderson** [comment]
Hi, this usually comes from a version mismatch. Can you check that you have got an Edinburgh (1.0) release of EdgeX? If you look at the log for core-metadata it should should show the version:
```
level=INFO ts=2019-07-22T10:37:17.971824409Z app=edgex-core-metadata source=main.go:58 msg="Service dependencies resolved..."
level=INFO ts=2019-07-22T10:37:17.976821712Z app=edgex-core-metadata source=main.go:59 msg="Starting edgex-core-metadata 1.0.1 "
level=INFO ts=2019-07-22T10:37:17.979455299Z app=edgex-core-metadata source=main.go:62 msg="This is the EdgeX Core Metadata Microservice"
level=INFO ts=2019-07-22T10:37:17.983832426Z app=edgex-core-metadata source=main.go:69 msg="Service started in: 13.293885ms"
level=INFO ts=2019-07-22T10:37:17.986429902Z app=edgex-core-metadata source=main.go:70 msg="Listening on port: 48081"
```

**Comment by debukhra** [comment]
Hi Iain,

Thanks for the suggestion. Yes as you rightly pointed out it was a version mismatch. I was using a different docker-compose file which caused this version mismatch. Now I could able to resolve the issue .Thanks for your help.
