### ISSUE TITLE
Add /api/version endpoint

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-c#166]
As per https://github.com/edgexfoundry/edgex-go/issues/1596
For the Device Services we'll add a field "sdk_version" to the returned object

**Comment by lenny-intel** [comment]
So device service's version endpoint returns the version of the SDK used rather than the version of the Device Service? What is the value of returning the SDK version?

**Comment by iain-anderson** [comment]
It returns both. Having the SDK version is useful for reproducing people's problems.

**Comment by iain-anderson** [comment]
Closed #167
