### ISSUE TITLE
Add Attribution.txt and LICENSE to all service artifacts

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/device-sdk-c#250]
### Affected Services
All device services

### Description
Per architect's meeting of 4/20/20, all artifacts (snaps, docker images, etc.) should include the LICENSE and Attribution.txt at the root directory of the image (same place that the binary is placed).

**Comment by iain-anderson** [comment]
@jpwhitemn  we don't generate artifacts for device-sdk-c - we do however provide a dockerfile for building a base image, ie a development system that includes the sdk headers and library. This includes Attribution and LICENSE files in /usr/local/share/device-sdk-c which I think is reasonable
