### ISSUE TITLE
Remove Logging Service (Device SDK C code clean up)

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-c#274]
Logging service is no longer supported so references need to be removed. This includes the Logging. EnableRemote config setting and possibly the whole [Logging] config section is we only support STDOUT. [Clients.Logging] section also needs to be removed. The LogLevel under Writable stays

**Comment by iain-anderson** [comment]
closed via #276

**Comment by lenny-intel** [comment]
FYI, we put this on hold for rest of EdgeX until Ireland due the backward compatibility.
