### ISSUE TITLE
Review sizes of configured integer values

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-c#28]
Each integral configuration value is currently typed as int64_t, and clearly this is not always appropriate. Most if not all should be unsigned, and port numbers in particular are 16-bit. This propagates through to some function parameters, eg the port number in edgex_consul_client_register_service().

**Comment by SteveOss** [comment]
@iain-anderson Is this an implementation decision or a restriction from Consul (or something else) ?

**Comment by iain-anderson** [comment]
This is as they come out from the toml parser. We just haven't done the necessary bounds-checking and casting yet.

**Comment by iain-anderson** [comment]
Addressed in https://github.com/edgexfoundry/device-sdk-c/pull/31
