### ISSUE TITLE
Add Tags to Event model

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-c#292]
The new Tags property has been added to the Event model on go-mo-core-contracts as a `map[string]string`. The C version of Event needs to be updated to have the Tags field.

**Comment by iain-anderson** [comment]
Remove the unused C representations of Event/Reading. Add a comment in the area of the marshaling code detailing the Event model.

**Comment by iain-anderson** [comment]
Closed #294
