### ISSUE TITLE
Docker build failing on absent yxml.h

### ISSUE THREAD

**Issue by kb2ma** [edgexfoundry/device-sdk-c#295]
Running `make docker` on a fresh checkout of master branch results in

```
[ 30%] Building C object c/CMakeFiles/csdk.dir/iot/data.c.o
/edgex-c-sdk/src/c/iot/data.c:9:10: fatal error: yxml.h: No such file or directory
    9 | #include "yxml.h"
      |          ^~~~~~~~
```

Looks like the immediate issue is commit IOTechSystems/iotech-c-utils@185010a2ff153e8410aad9e3072ae20fd4bfe1de from 2020-09-22.

**Comment by iain-anderson** [comment]
fixed #296
