### ISSUE TITLE
Is it possible to install edgex services without docker/docker images and run application?

### ISSUE THREAD

**Issue by malepurakesh** [edgexfoundry/device-sdk-c#318]
Hi, 
I have installed the EdgeX C SDK in my target board (RISCV architecture). And I followed [this](https://docs.edgexfoundry.org/1.2/getting-started/Ch-GettingStartedSDK-C/#customize-your-device-service) steps, I have compiled the example template.c . And I have installed docker and docker-compose. When I am trying to run the docker-compose up, I am facing the incompatible issues for redis and emqx/kuiper images. (These two are not supported RISCV) 
Is there any alternative for RISCV supported redis and emqx/kuiper docker services? If yes, what are those?. What images could be helpful, just replace the name of redis and kuiper in docker-compose.yml file ?

Is it possible to install all the docker services in my target and run the example application without using the docker(images/ docker-compose.yml file).

I am using docker-compose.yml file
uploaded with .txt format. Actual format is .yml
[docker-compose.txt](https://github.com/edgexfoundry/device-sdk-c/files/5801054/docker-compose.txt)

Thanks in advance.

**Comment by iain-anderson** [comment]
@lenny-intel I think the answer to this is that redis is required? Maybe better answered in developer-scripts?

**Comment by lenny-intel** [comment]
@malepurakesh, Redis is required, but Kuiper is not. You can check the Redis docker hub for alternative images that might work with `RISCV `.

**Comment by malepurakesh** [comment]
After putting the effort, I got to know we can run the edgex services without docker also. 

As we know docker is a container related thing. But few of the things (docker images) are not supported to RISC-V architecture. It may supported with customised images.

Without docker also we can run the EdgeX Services. We need to install the dependency packages, which all are required and build from the sources. The services are like [edgex-go services](https://github.com/edgexfoundry/edgex-go), [device-sdk-c](https://github.com/edgexfoundry/device-sdk-c) and [app-service-configurable](https://github.com/edgexfoundry/app-service-configurable). 

The thing is, with docker images all the services run by one short. Without docker we have to run multiple services individually. (Writing shell script is a good approach). 

To install the device-sdk-c, we need to add few lines in the Make and CMake files related to RISC-V. 

As I understood, database is mandatory thing while starting the EdgeX services. As shown in the EdgeX Foundry architecture diagram, core services are mandatory for EdgeX. So, we have to start the redis database server before starting the EdgeX Core services.

![EdgeX_architecture](https://user-images.githubusercontent.com/53519398/112821287-1e296e00-90a4-11eb-81c0-0233e254826d.png)

And about Kuiper, it is a edge analytics tool. It will be used to take decisions in edge device only, without sending the data to cloud and analyse there.
![kuiper_message_bus_flow](https://user-images.githubusercontent.com/53519398/112821993-fe467a00-90a4-11eb-9159-58d8e1c1f125.png)


I just shared my experience, If anything wrong please correct me. 
Thanks @iain-anderson  and @lenny-intel  for helping with your comments.
