### ISSUE TITLE
device sdk for micro controllers

### ISSUE THREAD

**Issue by malepurakesh** [edgexfoundry/device-sdk-c#330]
Hi 

As I found in google, regarding the edgex device service support for micro controllers was going to enabled. ([link](https://wiki.edgexfoundry.org/download/attachments/7602724/EdgeXJun2018-withUC.pdf?version=1&modificationDate=1530623408000&api=v2))  **"Planned work will enable C-based Device Services to be embedded in constrained microcontrollers running a RTOS for real-time use cases (e.g. within a smart sensor or PLC)"**. Is device service for micro controllers enabled or not. If it is enabled could you provide the reference link.

Thanks in advance

**Comment by iain-anderson** [comment]
Has not been done in EdgeX

**Comment by malepurakesh** [comment]
It was mentioned in EdgeX introduction, status & roadmap presentation ([06/30/2018](https://wiki.edgexfoundry.org/download/attachments/7602724/EdgeXJun2018-withUC.pdf?version=1&modificationDate=1530623408000&api=v2)). Is still C-based device service to embedded constrained micro controllers not enabled...? If is there any source, which can be available to port on MCU please share the reference. Thank you @iain-anderson

**Comment by iain-anderson** [comment]
Hi, this is still an aspiration, but there has not been a port as yet. Using FreeRTOS+POSIX may provide most of what is required, but that is still in development (FreeRTOS Labs).
My company has a commercial product that integrates with EdgeX and is targeted for constrained environments (currently available on the Zephyr RTOS) - message me on the EdgeX Foundry Slack if you are interested
