### ISSUE TITLE
How to update the topic for the exmaples?

### ISSUE THREAD

**Issue by wallace-hu** [edgexfoundry/device-sdk-c#338]
When i startup the edgeX service and run the examples under 
device-sdk-c/c/examples, The topic is hard-coded on the  App-Service-Config/configuration.toml  as below
      [Writable.Pipeline.Functions.MQTTSend.Addressable]
        Address=   "192.168.34.16"
        Port=      1883
        Protocol=  "tcp"
        Publisher= "AppServiceConfigurable-mqtt-export"
        User=      ""
        Password=  ""
        Topic=     "topic here"

I want each device has its own topic, But looks like the topic is hardcoded in the App-Service-Config/configuration.toml
Is there any way to modify the topic dynamically  when the examples are running?

**Comment by iain-anderson** [comment]
Hi, I don't think you can specify a topic for each device. Please open an issue in https://github.com/edgexfoundry/app-functions-sdk-go to request the feature, thanks
