### ISSUE TITLE
How to add a new tag on readings?

### ISSUE THREAD

**Issue by wallace-hu** [edgexfoundry/device-sdk-c#339]
As the examples showed, The edgeX  payloads always has below format which include <id, oigin, device, name, value>
Is there any way to add a more tag on the readings by modifying the config file or other way?: 
{
   "id":"315356d8-251c-4943-b2fb-e4b87abf2dd2",
   "device":"713b2d",
    "created":1617762421479,
    "origin":1617762421431744142, 
     "readings":[
            {
                "id":"f00b4d92-eb5a-4030-8cb6- 531c1d7a5974",
                "origin":1617762421431744142,
                "device":"713b2d",
                "name":"RSSI",
                "value":"48.00",
                "valueType":"String"
            }
      ]
}

**Comment by lenny-intel** [comment]
@wallace-hu , are you wanting to do this from Application Services? If so, see here for details of adding tags to Events from app service:
https://docs.edgexfoundry.org/1.3/microservices/application/AppServiceConfigurable/#addtags
https://docs.edgexfoundry.org/1.3/microservices/application/BuiltIn/#addtags

**Comment by wallace-hu** [comment]
Hi thanks for the comment,  Not sure i make myslef understood as i am new to EdgeX and I am just studying the examples under device-sdk-c-1.3.0/src/c/example/random.  As the initial cmment showed the random example publish message like that 
format. 
{
"id":"315356d8-251c-4943-b2fb-e4b87abf2dd2",
"device":"713b2d",
"created":1617762421479,
"origin":1617762421431744142,
"readings":[
{
"id":"f00b4d92-eb5a-4030-8cb6- 531c1d7a5974",
"origin":1617762421431744142,
"device":"713b2d",
"name":"RSSI",
"value":"48.00",
"valueType":"String"
}
]
}
In fact, I want to add a tag into the readings like:
{
"id":"315356d8-251c-4943-b2fb-e4b87abf2dd2",
"device":"713b2d",
"created":1617762421479,
"origin":1617762421431744142,
"readings":[
{
"id":"f00b4d92-eb5a-4030-8cb6- 531c1d7a5974",
"origin":1617762421431744142,
"device":"713b2d",
**"ADDTAGS":"VALUES"**
"name":"",
"value":"48.00",
"valueType":"String"
}
]
}


I have tried to modify the congifuragtion.toml per the upper link gudiance when statup the edgeX. But it didn‘t work.
--------------------------------------
[Writable]
  LogLevel = "INFO"

  [Writable.StoreAndForward]
    Enabled = false
    RetryInterval = "5m"
    MaxRetryCount = 10

  [Writable.Pipeline]
    ExecutionOrder = "TransformToJSON, MQTTSend, MarkAsPushed"

    [Writable.Pipeline.Functions.TransformToJSON]
    [Writable.Pipeline.Functions.MarkAsPushed]
    [Writable.Pipeline.Functions.FilterByDeviceName]
      [Writable.Pipeline.Functions.FilterByDeviceName.Parameters]
        DeviceNames = ""
        FilterOut = "false"
    [Writable.Pipeline.Functions.FilterByValueDescriptor]
      [Writable.Pipeline.Functions.FilterByValueDescriptor.Parameters]
        ValueDescriptors = ""
        FilterOut = "false"
    [Writable.Pipeline.Functions.AddTags]
      [Writable.Pipeline.Functions.AddTags.Parameters]
        tags = "GatewayId:HoustonStore000123,Latitude:29.630771,Longitude:-95.377603"
    [Writable.Pipeline.Functions.MQTTSend]
      [Writable.Pipeline.Functions.MQTTSend.Parameters]
        qos="0"
        key=""
        autoreconnect="false"
        retain="false"
        cert=""
        persistOnError = "false"
      [Writable.Pipeline.Functions.MQTTSend.Addressable]
        Address=   "192.168.34.16"
        Port=      1883
        Protocol=  "tcp"
        Publisher= "localhost"
        User=      ""
        Password=  ""
        Topic=     "temperaturedata2"

**Comment by lenny-intel** [comment]
@wallace-hu, the problem is you are working in the C Device SDK example, but using the App Service configuration.

What is your end goal? Are you expecting the Events to be exported out of Edgex with the tags?

Device Service don't not have a way to add tags to the Event. This is only a capability of App Services. Please review the Edgex Architecture here so you have a better understanding of how data flows through Edgex.
https://docs.edgexfoundry.org/1.3/#edgex-foundry-service-layers

**Comment by wallace-hu** [comment]
Thank you,  It looks like the JASON data format can't be changed.

**Comment by wallace-hu** [comment]
HI  I re-open this bug as i have fixed it.
In #comment3, I have a missing.
Wrong line:
[Writable.Pipeline]
ExecutionOrder = "TransformToJSON, MQTTSend, MarkAsPushed"

Should be 
[Writable.Pipeline]
ExecutionOrder = "Addtags,TransformToJSON, MQTTSend, MarkAsPushed"
