### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by lazy-wangxl** [edgexfoundry/device-sdk-c#358]
In function **get_handler**:
using **iot_data_alloc_*** series functions, and when to free memory?

I created 2000 collection points，and running about 30min, The process memory takes up about 50% (top , total: 2G)

**device-sdk-c version: v1.3.0**

**my code:**
`static bool
commclient_get_handler( void *impl, const char *devname,
        const devsdk_protocols *protocols, uint32_t nreadings,
        const devsdk_commandrequest *requests, devsdk_commandresult *readings,
        const devsdk_nvpairs *qparms,
        iot_data_t **exception )
{
    S_COMMCLIENT_DRIVER *driver = (S_COMMCLIENT_DRIVER *)impl;

    double dbData = 123;
    for (uint32_t i = 0; i < nreadings; ++i) {

        switch (iot_typecode_type(requests->type))
        {
        case IOT_DATA_INT8:  /**< Signed 8bit integer */
            readings[i].value = iot_data_alloc_i8(static_cast<int8_t>(dbData));
            break;
        case IOT_DATA_UINT8:  /**< Unsigned 8bit integer */
            readings[i].value = iot_data_alloc_ui8(static_cast<uint8_t>(dbData));
            break;
        case IOT_DATA_INT16:  /**< Signed 16bit integer */
            readings[i].value = iot_data_alloc_i16(static_cast<int16_t>(dbData));
            break;
        case IOT_DATA_UINT16:  /**< Unsigned 16bit integer */
            readings[i].value = iot_data_alloc_ui16(static_cast<uint16_t>(dbData));
            break;
        case IOT_DATA_INT32:  /**< Signed 32bit integer */
            readings[i].value = iot_data_alloc_i32(static_cast<int32_t>(dbData));
            break;
        case IOT_DATA_UINT32:  /**< Unsigned 32bit integer */
            readings[i].value = iot_data_alloc_ui32(static_cast<uint32_t>(dbData));
            break;
        case IOT_DATA_INT64:  /**< Signed 64bit integer */
            readings[i].value = iot_data_alloc_i64(static_cast<int64_t>(dbData));
            break;
        case IOT_DATA_UINT64:  /**< Unsigned 64bit integer */
            readings[i].value = iot_data_alloc_ui64(static_cast<uint64_t>(dbData));
            break;
        case IOT_DATA_FLOAT32:  /**< 32bit float */
            readings[i].value = iot_data_alloc_f32(static_cast<float>(dbData));
            break;
        case IOT_DATA_FLOAT64:  /**< 64bit float */
            readings[i].value = iot_data_alloc_f64(dbData);
            break;
        case IOT_DATA_BOOL:  /**< Boolean */
            readings[i].value = iot_data_alloc_bool(dbData ? true : false);
            break;
        case IOT_DATA_STRING:  /**< String */
            readings[i].value = iot_data_alloc_string(std::to_string(dbData).c_str(), IOT_DATA_REF);
            break;
        case IOT_DATA_ARRAY:  /**< Array */
        case IOT_DATA_MAP:  /**< Map */
        case IOT_DATA_VECTOR:  /**< Vector */
            comm_debug(LOG_LEVEL_ERROR, "Value type is 'Array'/'Map'/'Vector'");
            break;
        default:
            comm_debug(LOG_LEVEL_ERROR, "Value type is Error! ");
            break;
        }
    }

    return true;
}`

**Device AutoEvent like this:**
` "autoEvents": [
        {
            "frequency": "1s",
            "resource": "Tag1"
        },
        {
            "frequency": "1s",
            "resource": "Tag2"
        },
        {
            "frequency": "1s",
            "resource": "Tag3"
        },
        {
            "frequency": "1s",
            "resource": "Tag4"
        },
        {
            "frequency": "1s",
            "resource": "Tag5"
        },
        {
            "frequency": "1s",
            "resource": "Tag6"
        },
        {
            "frequency": "1s",
            "resource": "Tag7"
        },
        {
            "frequency": "1s",
            "resource": "Tag8"
        },
        {
            "frequency": "1s",
            "resource": "Tag9"
        },
        {
            "frequency": "1s",
            "resource": "Tag10"
        },
        {
            "frequency": "1s",
            "resource": "Tag11"
        },
        {
            "frequency": "1s",
            "resource": "Tag12"
        },
        {
            "frequency": "1s",
            "resource": "Tag13"
        },
        {
            "frequency": "1s",
            "resource": "Tag14"
        },
        {
            "frequency": "1s",
            "resource": "Tag15"
        },
        {
            "frequency": "1s",
            "resource": "Tag16"
        },
        {
            "frequency": "1s",
            "resource": "Tag17"
        },
        {
            "frequency": "1s",
            "resource": "Tag18"
        },
        {
            "frequency": "1s",
            "resource": "Tag19"
        },
       ... ...
      `

**Comment by lazy-wangxl** [comment]
I found it wasn't iot_ data_ alloc_* , but when the device service sends data.

**Comment by lindseysimple** [comment]
@FelixTing Please investigate further.

**Comment by FelixTing** [comment]
Memory leak after device service sends data is no longer observed in v3.
