### ISSUE TITLE
Bug: Configuring for MessageQueue on MQTT results in segfault

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-c#361]
MQTT driver uses the old [Service]/Timeout and [Service]/ConnectRetries configuration elements which no longer exist in v2.0
This causes a segfault in messagequeue initialization.

**Comment by nil4git** [comment]
Hi Team,
Can you please review the same
Thanks

**Comment by iain-anderson** [comment]
closed #365
