### ISSUE TITLE
Device service SDK should support REST PATCH API to update service configurations

### ISSUE THREAD

**Issue by anilchoudhury** [edgexfoundry/device-sdk-c#368]
Currently the device SDK only supports REST APIs to get the service config.
It does not support any REST API option to update it. Same is the case with SMA. 

I think if we can't change service config, it makes little sense as we can't enable controlling these services from cloud or other places.
We are seriously looking for this feature as we need to control configuration of these services from Web-UI or cloud.

In addition to this, we are looking for support of custom configurations in service configuration file. I understand that you support custom service configurations at runtime https://github.com/edgexfoundry/device-sdk-c/blob/main/src/c/examples/template.c#L283 but we need to define default settings and option to control them at runtime.

**Ex**:
If we are running a NTP server as a service. We need to store NTP settings like NTP servers, mode etc. to the service config file and later these can be updated from Web UI or cloud.

**Comment by lenny-intel** [comment]
@anilchoudhury , configuration can be modified in Consul Configuration Provider).
https://docs.edgexfoundry.org/2.0/microservices/configuration/ConfigurationAndRegistry/#configuration
Changes to items under `[Writable]` are dynamic other require the service to be restarted to take effect.

**Comment by darjip** [comment]
@lenny-intel ,  I have observed that consul does not persist the configuration across the docker restart? does it need any extra configuration to make configuration persist?

**Comment by lenny-intel** [comment]
Configuration is persisted via Docker volumes. If you remove the volume between restarts you will loose your data. 
How are you doing you docker restarts?

**Comment by anilchoudhury** [comment]
HI @lenny-intel 
We are working in monolithic build mode.
We expect consul to store the data into its database.

**Comment by anilchoudhury** [comment]
Hi @lenny-intel ,
We run docker-compose down and then up command to start all containers.
I can see our kuiper rules persist across down and up and even if i reboot the raspberry PI.

**Comment by darjip** [comment]
@lenny-intel , just docker-compose down and up

**Comment by lenny-intel** [comment]
@anilchoudhury , @darjip , this thread has diverted from the original topic of this issue. Please start a new issue or better slack post in #Core channel to continue this thread.

**Comment by iain-anderson** [comment]
closing: config updates are handled via registry / consul

**Comment by anilchoudhury** [comment]
Hi @lenny-intel we can update any service configurations from consul webUI. But in a release mode, we can't access consul from outside. In that case, how can we update a service configuration?
We got the consul APIs to get any service config data recursively or non-recursively but it provides the value in encrypted format.
How can an external module decrypt the values for the keys received?

**Comment by lenny-intel** [comment]
@anilchoudhury , it is not encrypted, just base64 encoded.
https://www.consul.io/api-docs/kv#read-key

**Comment by anilchoudhury** [comment]
Oh sorry for the confusion.

**Comment by lenny-intel** [comment]
@anilchoudhury , @darjip , I have recreated the Consul persistence issue you have seen. Not sure when this started happening. The solution is to add the following to the consul service in the compose file. Please try this and let me know if it resolves your issue:

```
command: "agent -ui -bootstrap -server -client 0.0.0.0"
```
