### ISSUE TITLE
URL to see the event/reading data that the service is generating and sending to EdgeX isn't displaying.

### ISSUE THREAD

**Issue by Rakshithakrishna2** [edgexfoundry/device-sdk-c#369]
In Ireland document of EdgeX, in the below mentioned path,
https://docs.edgexfoundry.org/2.0/getting-started/Ch-GettingStartedSDK-C/,

In order to, see the event/reading data that the service is generating and sending to EdgeX an URL is mentioned, as below
http://localhost:59880/api/v2/event/device/RandNum-Device01/100
On running all the services, and checking on browser using above below link with modified as
http://10.168.2.71:59880/api/v2/event/device/RandNum-Device01/100 , the page is blank. ( No random value is displaying).

Even checked (trial and error method), with port numbers of core data (59880), core metadata-59881 (getting page not found), core-command (59882) and 59992 (blank page).

But when used the curl link given in point 5 in the document (link given above): Changed as below,
10.168.2.71:59992/api/v2/device/name/RandNum-Device01/RandomNumber

I could able to see the random number in Raw data. Have given the image below.

![Screenshot from 2021-08-30 11-38-48](https://user-images.githubusercontent.com/88701371/131295084-dc1eeca9-6e87-4b78-8351-f8544703c899.png)

Please verify and let us know if any corrections need to be made.
Thank you.

**Comment by iain-anderson** [comment]
I think the URL in the documentation should be changed to:

http://localhost:59880/api/v2/event/device/name/RandNum-Device01?limit=100

Can you confirm that this works for you?

**Comment by Rakshithakrishna2** [comment]
Hi @iain-anderson, I could able to see results with that link, but the I am not getting results till limit =100, I have attached image, could you please see and let me know.
![Screenshot from 2021-09-01 09-16-49](https://user-images.githubusercontent.com/88701371/131608872-ca6dda17-d3bf-47d2-98ab-7365c02a70b6.png)

**Comment by Rakshithakrishna2** [comment]
Hi @iain-anderson , I am able to get data till the limit specified.
Thanks for the support

**Comment by iain-anderson** [comment]
Corrected via https://github.com/edgexfoundry/edgex-docs/pull/556
