### ISSUE TITLE
Device service with resgistry option gives curl error

### ISSUE THREAD

**Issue by darjip** [edgexfoundry/device-sdk-c#371]
Running default template service with registry, starting service with "-r" option, getting error during the start of service
 "curl failed with code 52, (Server returned nothing no headers , no data) , Consul is used as a registry , listening on port 8500, same configuration set in device services (.toml)

**Comment by darjip** [comment]
Let me share the environment details, the edgex core services are running in docker mode and and we have compiled device-sdk-c separately and running template device service with registry option, there we face this curl failed error

**Comment by iain-anderson** [comment]
closing - superseded by #375
