### ISSUE TITLE
Feature: Individual Configuration Parameters REST GET/PUT request should be entertained for Device C SDK

### ISSUE THREAD

**Issue by nil4git** [edgexfoundry/device-sdk-c#373]
Configuration.toml parameters should be supporting REST API's for individual GET as well as PUT request
With this, the configuration.toml parameters can be changed on the fly via REST PUT request and the notification can be sent to device service application
Decision making logic will be left with Device service application who can then decide whether he needs a reboot/re-instantiate himself or can continue working with considering the new updated value/s

P.S : We @ Eaton have developed the same for our own usecase satisfaction

**Comment by iain-anderson** [comment]
Updates to configurations of all EdgeX services is handled via registry (Consul). Device services may take new configurations without restart via this method. See also #368

**Comment by nil4git** [comment]
Is it able to edit all configuration.toml parameters and revert back to user about the change notification?

**Comment by iain-anderson** [comment]
Changes to parameters under `Writable` are notified back to the service. Changes under `Writable/Driver` are notified to the implementation (others are handled within the SDK)
