### ISSUE TITLE
Starting Device service with registry option gives error"no endpoint for core-data and core-metadata"

### ISSUE THREAD

**Issue by darjip** [edgexfoundry/device-sdk-c#375]
Just running template device service with registry option i.e. "-r", getting the error "no service endpoint for core-data and core-metadata".

The endpoint is mentioned in a particular configuration.toml file.

Device service could able to upload the configuration to consul, but later it gives above error and  exit from there

**Comment by iain-anderson** [comment]
When running with -r the endpoints for core-data / core-metadata are obtained from consul rather than from configuration. This requires that core-data and core-metadata have also been run with -r which causes them to register their endpoints

**Comment by darjip** [comment]
Oh ok got it, in our system the core-data and core-metadata running without a registry in the system, Let me try running the edgex services with registry option, and will share the result with you. Thanks for the quick response
