### ISSUE TITLE
Template device service does not connect to consul, if HOST configuration is "0.0.0.0"

### ISSUE THREAD

**Issue by darjip** [edgexfoundry/device-sdk-c#377]
Trying to run template device service with consul , here the the template devicce service configuration having HOST = "0.0.0.0", that means it is reachable outside the device, we can ping, GET config of device service from another host. 
Here consul is also bind to "0.0.0.0" address. 
While starting template device service with consul registry , it is not able to connect to consul, getting 400 error :
`level=DEBUG ts=2021-08-17T18:07:34Z app=device-template msg="HTTP response: 400"
level=ERROR ts=2021-08-17T18:07:34Z app=device-template msg="Register service failed: Invalid service address"
level=ERROR ts=2021-08-17T18:07:34Z app=device-template msg="Unable to register service in registry"
Error: 21: HTTP request failed
`

Consul and device service are running in same host, but If I remove HOST field from the configuration.toml file of device-template, it is able to connect to consul.

**Comment by iain-anderson** [comment]
Host should be set to the address at which other services (eg, Consul, core-command) can connect to the device service - so "0.0.0.0" isn't really valid.
To configure the address on which the service listens, set `[Service]/ServerBindAddr`  or `SERVICE_SERVERBINDADDR`

**Comment by darjip** [comment]
Yes , with 127.0.0.1, it is able to connect to consul, but we can not access the device service from outside world. (i..eREST  ping, GET config etc...)

**Comment by iain-anderson** [comment]
Set host to 127.0.0.1 and the bind address to 0.0.0.0
