### ISSUE TITLE
Add CORS support

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/device-sdk-c#389]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...
Add configurable CORS implementation

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
See go-mod-core-contracts PRs 286, 288, 290 - we should have equivalent functionality to this

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by iain-anderson** [comment]
closed #406

**Comment by bhardwajvanshika-eaton** [comment]
above fix is not working for me?

**Comment by cloudxxx8** [comment]
@bhardwajvanshika-eaton you may open a new issue with more context.
