### ISSUE TITLE
Hi, do we have device-sdk-c build for device-virtual, device-modbus also or only for device-template? Please let me know for any suggestions. Thanks in advance.

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/device-sdk-c#400]
# 📚 Docs or Wiki Bug Report

### Description [**REQUIRED**]

 A clear and concise description of the problem...

### What's the affected URL? [**REQUIRED**]
 https://docs.edgexfoundry.org/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by dipshirajput** [comment]
@jpwhitemn @iain-anderson @SteveOss @JPWKU @lenny-intel  please let me know for any suggestions. Thanks in advance.

**Comment by lenny-intel** [comment]
Answered in slack
