### ISSUE TITLE
HTTP callbacks return "no content" instead of "ok" + BaseResponse

### ISSUE THREAD

**Issue by eaton-coreymutter** [edgexfoundry/device-sdk-c#419]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-sdk-c callback2.c

### Is this a regression?

 Unknown

### Description and Minimal Reproduction [**REQUIRED**]

In callback2.c we respond to core-metadata's callbacks for device and deviceprofile (possibly others) with 204 No Content.
I checked the API doc in device-sdk-go and it says we should be returning 200 OK and a BaseResponse.
PutRequest() (and all the other request types I think) in go-mod-core-contracts returns an error because it tries to parse the nonexistent response as JSON.

## 🔥 Exception or Error
<pre><code>

level=ERROR ts=2022-06-15T19:24:44.251013538Z app=core-metadata source=notify.go:115 msg="fail to invoke device service callback for updating device profile KXjSxv0C, err: failed to parse the response body -> unexpected end of JSON input"
</code></pre>
(the callback is actually processed fine in the device service)

## 🌍  Your Environment
**Deployment Environment:**
Yocto, no containers

**EdgeX Version [**REQUIRED**]:**
2.0.0 + a few fixes

**Anything else relevant?**
I have not yet tried changing this locally. I can post a fix PR, if this analysis is correct. It might be a few days though.

**Comment by iain-anderson** [comment]
See also https://github.com/edgexfoundry/device-sdk-go/pull/701 where this was changed / fixed in the Go SDK
