### ISSUE TITLE
HTTP callbacks for update-profile and update-service not working

### ISSUE THREAD

**Issue by eaton-coreymutter** [edgexfoundry/device-sdk-c#420]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: device-sdk-c callback2.c

### Is this a regression?

 Unknown

### Description and Minimal Reproduction [**REQUIRED**]

Updates to device profiles don't appear in the data returned by edgex_profiles(). 

## 🔥 Exception or Error

We see "callback: Updated device profile " messages in the device service info log (the profile name is omitted despite being present in the HTTP request body). When updating adminState or operatingState we don't see any info messages in the log.

## 🌍  Your Environment
**Deployment Environment:**
Yocto, no containers

**EdgeX Version [**REQUIRED**]:**
2.0.0 + a few fixes

**Anything else relevant?**

Somewhat related to #419, I'll post a PR to fix both. This seems to be a missing v1->v2 update - those two callbacks are expecting the profile/service in the top-level JSON object, instead of inside an object named "profile" or "service". The JSON read functions return no error in this case, they just don't find or populate any fields.

**Comment by iain-anderson** [comment]
closed #421
