### ISSUE TITLE
[C] Switch TOML files to be YAML files

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/device-sdk-c#438]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for Device and configuration files

### Description [**REQUIRED**]
 It was decided in Minnesota planning that all TOML files would be changed to be YAML

### Describe the solution you'd like
 Device and Configuration files need be converted from TOML to YAML

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by iain-anderson** [comment]
closed #455
