### ISSUE TITLE
CMake failed : Could NOT find IOT (missing: IOT_LIBRARY IOT_INCLUDE_DIR)

### ISSUE THREAD

**Issue by HCL-BMC** [edgexfoundry/device-sdk-c#446]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
   I cloned latest upstream BLE device service code and device-sdk-c.
   https://github.com/edgexfoundry-holding/device-bluetooth-c 
   https://github.com/edgexfoundry/device-sdk-c

   I Installed all the dependency packages and libraries.

   While give make command in  device-sdk-c code, getting below error.
   
   "kumar@kumar-ThinkPad-X1-Yoga-1st:~/Kumar/EdgeX/device-sdk-c$ make
./scripts/build.sh
+ CPPCHECK=false
+ DOCGEN=false
+ CMAKEOPTS=-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+ TOMLVER=SDK-0.2
+ CUTILVER=1.4
+ [ 0 -gt 0 ]
+ readlink -f ./scripts/build.sh
+ dirname /home/kumar/Kumar/EdgeX/device-sdk-c/scripts/build.sh
+ dirname /home/kumar/Kumar/EdgeX/device-sdk-c/scripts
+ ROOT=/home/kumar/Kumar/EdgeX/device-sdk-c
+ cd /home/kumar/Kumar/EdgeX/device-sdk-c
+ [ ! -d deps ]
+ mkdir -p /home/kumar/Kumar/EdgeX/device-sdk-c/build/release
+ cd /home/kumar/Kumar/EdgeX/device-sdk-c/build/release
+ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release /home/kumar/Kumar/EdgeX/device-sdk-c/src
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find IOT (missing: IOT_LIBRARY IOT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIOT.cmake:4 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/kumar/Kumar/EdgeX/device-sdk-c/build/release/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:13: build] Error 1
"

 I tried to install IOT related libraries and couldn't find the IOT libraries and header files.
 
 Any suggestions on this ?

**Anything else relevant?**

**Comment by iain-anderson** [comment]
Need to update README etc as to how to obtain IOT
@HCL-BMC what linux distribution are you running?

**Comment by iain-anderson** [comment]
```
curl -fsSL https://iotech.jfrog.io/artifactory/api/gpg/key/public | sudo gpg --dearmor -o /usr/share/keyrings/iotech.gpg
echo "deb [signed-by=/usr/share/keyrings/iotech.gpg] https://iotech.jfrog.io/iotech/debian-release $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/iotech.list
apt update
apt install iotech-iot-1.4-dev
```

**Comment by HCL-BMC** [comment]
Thanks a lot. I installed it and make completed.
