### ISSUE TITLE
Errors while making build on Raspberry pi Ubuntu version 22.04

### ISSUE THREAD

**Issue by pranitsuperb** [edgexfoundry/device-sdk-c#448]
Hello there,

I have followed the steps of prerequisites and requirements as stated in the readme. I have got the following error while building the make on device-sdk-c directory. .....................

./scripts/build.sh
+ CPPCHECK=false
+ DOCGEN=false
+ CMAKEOPTS=-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
+ TOMLVER=SDK-0.2
+ CUTILVER=1.4
+ [ 0 -gt 0 ]
+ readlink -f ./scripts/build.sh
+ dirname /root/device-sdk-c/scripts/build.sh
+ dirname /root/device-sdk-c/scripts
+ ROOT=/root/device-sdk-c
+ cd /root/device-sdk-c
+ [ ! -d deps ]
+ mkdir -p /root/device-sdk-c/build/release
+ cd /root/device-sdk-c/build/release
+ cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Release /root/device-sdk-c/src
CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find IOT (missing: IOT_LIBRARY IOT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindIOT.cmake:4 (find_package_handle_standard_args)
  CMakeLists.txt:50 (find_package)

I really appreciate your support in this regard. Thank you!

**Comment by iain-anderson** [comment]
Hi, see the comments in https://github.com/edgexfoundry/device-sdk-c/issues/446 for how to install the pre-requisite - but note that as of the most recent update the requirement is for version 1.5 rather than 1.4

Will add installation instructions in the README asap

**Comment by iain-anderson** [comment]
Documentation on installing the utilities added in #450
