### ISSUE TITLE
create_addressable failed issue.

### ISSUE THREAD

**Issue by HCL-BMC** [edgexfoundry/device-sdk-c#451]
**Getting this issue when we run device-ble binary with device-sdk-c v1.1.1 and device-sdk-c v1.3.0.
Seems like this url is not valid. - (http://localhost:59881/api/v1/addressable/).**

**Error Log :**

kumar@kumar-ThinkPad-X1-Yoga-1st:~/Kumar/EdgeX/device-bluetooth-c$ ./build/release/device-ble/device-ble 
Main func starts 
level=INFO ts=2023-03-27T08:24:30Z app=device-ble msg="iot_threadpool_alloc (threads: 8 max_jobs: 0 default_priority: -1 affinity: -1)"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-0 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-1 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-2 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-4 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-3 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-5 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-6 starting"
level=DEBUG ts=2023-03-27T08:24:30Z app=device-ble msg="Thread iot-0-7 starting"
level=INFO ts=2023-03-27T08:24:30Z app=device-ble msg="iot_scheduler_alloc (priority: -1 affinity: -1)"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="iot_threadpool_start()"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=TRACE ts=2023-03-27T08:24:30Z app=device-ble msg="Thread waiting for new job"
level=INFO ts=2023-03-27T08:24:30Z app=device-ble msg="Setting LogLevel to WARNING"
level=ERROR ts=2023-03-27T08:24:30Z app=device-ble msg="create_addressable failed"
Error: 21: HTTP request failed

**Comment by iain-anderson** [comment]
that's an old and unsupported version, but it should work so long as you are running core-metadata etc from the Hanoi (EdgeX 1.3) release

**Comment by HCL-BMC** [comment]
With Edgex Hanoi version also getting same issue.

level=ERROR ts=2023-03-29T05:48:12Z app=device-ble msg="create_addressable failed"
Error: 21: HTTP request failed

**Comment by iain-anderson** [comment]
Hi, I've run the CSDK example (device-template) at v1.3.1 versus edgex-go also at v1.3.1 and it seems ok. The default port for core-metadata on 1.3.1 should be 48081, not 59881 - maybe that's the problem?

**Comment by HCL-BMC** [comment]
@iain-anderson , Thanks for your response.

I am running device-ble generated from souce (https://github.com/edgexfoundry-holding/device-bluetooth-c) with device-sdk-c(1.3.1) and edgex-go(1.3.1).

**In, edgex-go (1.3.1) and other latest versions,  micro services is not running and getting below warning.**

level=WARN ts=2023-04-06T05:18:30.118111707Z app=core-metadata source=database.go:91 msg="couldn't retrieve database credentials: InsecureSecrets missing from configuration"

Could you please provide any suggestions on this.

**Comment by iain-anderson** [comment]
Could you ask the above question in https://github.com/orgs/edgexfoundry/discussions pls

**Comment by HCL-BMC** [comment]
Sure. Thanks.

**Comment by iain-anderson** [comment]
continued in https://github.com/orgs/edgexfoundry/discussions/87
