### ISSUE TITLE
The slash of a string cannot be removed using json_serialize_to_string

### ISSUE THREAD

**Issue by ych988** [edgexfoundry/device-sdk-c#492]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
reqdata.c

### Is this a regression?
no

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

    JSON_Value *value = json_object_get_value(data->json, name);
    if (value) {
      result = json_serialize_to_string(value);
    }
</code></pre>

IF the put request's json payload is string type, The slash of a string cannot be removed using json_serialize_to_string.
example: {"command": "open"} → Escape→ {\\"command\\": \\"open\\"} →json_serialize_to_string→ \open\
----
String value of result will be  \open\.  So that， still use json_object_get_string when json value is string types.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**
main

**Anything else relevant?**

**Comment by FelixTing** [comment]
fixed by #505
