### ISSUE TITLE
Program crashed because edgex_autoimpl released before asynchronous task execution.

### ISSUE THREAD

**Issue by ych988** [edgexfoundry/device-sdk-c#494]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: 
autoevent.c

### Is this a regression?
no

 Yes, the previous version in which this bug was not present was: ....

## 🔥 Exception or Error
<pre><code>

static void *ae_runner (void *p)
{
  edgex_autoimpl *ai = (edgex_autoimpl *)p;
  atomic_fetch_add (&ai->refs, 1);

  edgex_device *dev = edgex_devmap_device_byname (ai->svc->devices, ai->device);
  if (dev)
....
</code></pre>

The callback function ae_runner can be executed by threadpool. This case is asynchronous task.

If device deleted before the excution of the above code "atomic_fetch_add (&ai->refs, 1);", the edgex_autoimpl data maybe released prematurely.  So that, the program will crash due to accessing illegal memory.

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version [**REQUIRED**]:**

**Anything else relevant?**
We also have to modify iotech-c-utils to resolve this problem.  
Reference to: https://github.com/IOTechSystems/iotech-c-utils/issues/319

device-sdk-c may modify like this：
autoevent.c 
add blow three callback function
//add started
static void notify_schedule_run(void *p)
{
  edgex_autoimpl *ai = (edgex_autoimpl *)p;
  atomic_fetch_add (&ai->refs, 1);
}

static void notify_schedule_run_finish(void *p)
{
  edgex_autoimpl *ai = (edgex_autoimpl *)p;
  edgex_autoimpl_release (ai);
}

static void notify_schedule_abort(void *p)
{
  edgex_autoimpl *ai = (edgex_autoimpl *)p;
  edgex_autoimpl_release (ai);
}
//add end

    ae->impl->handle = iot_schedule_create
      (svc->scheduler, ae_runner, NULL, ae->impl, IOT_MS_TO_NS(ae->impl->interval), 0, 0, svc->thpool, -1);
//add started
    iot_schedule_add_run_callback(ae->impl->svc->scheduler, ae->impl->handle, notify_schedule_run);
    iot_schedule_add_run_finish_callback(ae->impl->svc->scheduler, ae->impl->handle, notify_schedule_run_finish);
    iot_schedule_add_abort_callback(ae->impl->svc->scheduler, ae->impl->handle, notify_schedule_abort);
    iot_schedule_add (ae->impl->svc->scheduler, ae->impl->handle);
//add end

**Comment by FelixTing** [comment]
Verified that this issue can occur with a typical autoevent. As @ych988 mentioned, when the autoevent runner is executing this line:
https://github.com/edgexfoundry/device-sdk-c/blob/1a776ee907d08e39928eb07fc2284b30a6e0a694/src/c/autoevent.c#L49
The reference count for edgex_autoimpl has not yet been increased. At this point, if the device is deleted, the edgex_autoimpl will be released.

The solution proposed by @ych988 is to increase the reference count when a schedule is run. It seems feasible.
@iain-anderson What is your take on this?

**Comment by cloudxxx8** [comment]
since this only happens after the device removement and the workaround is to restart the device service, this issue should not block the v3.1 release.
we are putting this into the backlog.

**Comment by iain-anderson** [comment]
The refcount in the impl structure is a legacy of the earlier scheduler implementation. The current scheduler has internal refcounting which should avoid this race condition.
I think the approach to fixing this is
* remove the refcount
* specify the free function for the impl structure when creating a schedule
* only call the free function ourselves in the case where the ae_starter / ae_stopper are defined, ie we aren't using the scheduler
