### ISSUE TITLE
Only 20 devices are cached when device service starts

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/device-sdk-c#510]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: C Device Service

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction [**REQUIRED**]
See https://github.com/orgs/edgexfoundry/discussions/187#discussioncomment-7236669

## 🌍  Your Environment
**Deployment Environment:** Ubuntu:22.04

**EdgeX Version [**REQUIRED**]:** main

**Comment by eaton-coreymutter** [comment]
I was bringing in another bugfix and saw this issue, we had a fix locally for a while so I posted a PR with it.

**Comment by FelixTing** [comment]
fixed by https://github.com/edgexfoundry/device-sdk-c/pull/518
